### ISSUE TITLE
Bulk Move not working

### ISSUE THREAD

**Issue by timonson** [huijunchen9260/dmenufm#26] opened 2019-12-18 11:19 UTC
Hi, I love your **dmenufm** script but I can't get the `bulk move` command of both MVV and YAK to work. Although I can select files, it seems that there is a bug in the script when selecting a destination. 

Let me know if you need more information or you can't replicate the error.
Thanks!

**Comment by terminalforlife** [comment] 2019-12-18 11:42
Can you run dmenufm in a terminal, then paste the output you get here?

**Comment by timonson** [comment] 2019-12-18 13:46
I got the files to move now and the terminal output is one file which I could select. I guess this selection prompt is the reason why it is confusing to me. Why can I select a single file from the bulk of files which I selected before? And then it moves all files anyway.

**Comment by huijunchen9260** [comment] 2019-12-18 15:02
May I ask which branch of dmenufm are you using right now? The master branch or the MultiScripts branch?

I tried on both branches and I cannot reproduce your error, I would like to know:

Are you using my newest commit in either branch?
What is the filename?
What is the directory name?
Does green prompt with "Selected to move" listed all your selected files? 
Does the yellow destination prompt appear?
Does the notification prompt appear?

Thank you!

**Comment by timonson** [comment] 2019-12-18 16:39
I use the master branch and the last commit. The filename and directory name have no weird parts (no spaces etc.).

Everything seems to work the way like I would expect it until the point where the green prompt with the text `Selected files (Enter to continue)` appears. In this prompt I **have to** select one of the displayed files to continue. When I press enter the selected file is printed to the terminal and I am forwarded to the next prompt where I can chose a destination. The files are then moved to the correct place. But like I said, the part where the green prompt appears is weird.

**Comment by huijunchen9260** [comment] 2019-12-18 17:02
That is exactly what I intended to, thanks to  @VebbNix. That green prompt with `Selected files (Enter to continue)` shows the list of the files that user chose and prevent user from choosing the files that is not intended.

I think this function is good, and I don't want to cancel it, but maybe we can change it so that it can be more useful. Do you think changing the color to the notification prompt would help? Or change the content of the green prompt?

Thanks!

**Comment by timonson** [comment] 2019-12-18 17:20
Thank you, now I understand what you did there. The fact that dmenu has no option to prompt only text without having to select an *item* was confusing to me. I am not so familiar with dmenu and therefore I was asking myself why I have to select a file again. But your reason, that you want to display a summary of the selected files, makes total sense. 
I just checked and dmenu really has no option to prompt **only** text. The best thing I come up with right now is changing your prompt *description* from `Selected files (Enter to continue)` to something like `Check files and press enter`.

**Comment by huijunchen9260** [comment] 2019-12-18 19:46
Fixed by the new commit in MultiScripts branch 
https://github.com/huijunchen9260/dmenufm/commit/987b106408beaaa00d3745a5af11dab4a611d27f

**Closed by huijunchen9260** 2019-12-18 19:46 UTC
